nodes:
  c022: [-0.71, -2.33, 0]
  c018: [-5.42, -8.83, 0]
  c019: [-8.09, -13.90, 0]
  c017: [ -11.18,  -18.57, 0]
  c016: [-15.69, -24.66, 0]
  c015: [-17.23, -27.97, 0]
  c014: [-22.16, -34.77, 0]
  c013: [-24.29, -39.15, 0]
  c012: [-29.44, -46.13, 0]
  square_inter_1: [-31.5, -49, 0]
  common_area_entrance: [-38.75, -44.28, 0]
  common_area_exit: [-53.09, -34.78, 0]
  square_inter_2: [-60, -30, 0]
  c058: [-54.41, -20.59, 0]
  c060: [-51.11, -15.48, 0]
  c062: [-45.31, -6.34, 0]
  c063: [-43.91, -5.11, 0]
  c064: [-41.33, 0, 0 ]
  square_inter_3: [-37.5, 5, 0]
  glass_corridor_entrance: [-30.77, 2.67, 0]
  glass_corridor_exit: [-11.71, -3.32, 0]
  main_entrance: [-15.17, -60.08, 0]
  elevator_1: [-8.59, -66.21, 0]
  atm: [-13, -70, 0]
  mensa_entrance: [-16.95, -76.81, 0]
  vending_machine: [-31.07, -102.69, 0]
  A049: [-33.04047, -107.2446, -0.1973825]
  A045: [ -58.36, -141.96, 0]
  street_end: [-63, -145, 0]
edges:
  - [c022, c018]
  - [c018, c019]
  - [c019, c017]
  - [c017, c016]
  - [c016, c015]
  - [c015, c014]
  - [c014, c013]
  - [c013, c012]
  - [c012, square_inter_1]
  - [square_inter_1, common_area_entrance]
  - [common_area_entrance, common_area_exit]
  - [common_area_exit, square_inter_2]
  - [square_inter_2, c058]
  - [c058, c060]
  - [c060, c062]
  - [c062, c063]
  - [c063, c064]
  - [c064, square_inter_3]
  - [square_inter_3, glass_corridor_entrance]
  - [glass_corridor_entrance, glass_corridor_exit]
  - [glass_corridor_exit, c022]
  - [square_inter_1, main_entrance]
  - [main_entrance, elevator_1]
  - [elevator_1, atm]
  - [atm, mensa_entrance]
  - [mensa_entrance, vending_machine]
  - [vending_machine, A049]
  - [A049, A045]
  - [A045, street_end]
